# Generated by Django 2.1.5 on 2019-02-10 14:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QName', models.CharField(max_length=40)),
                ('QCode', models.CharField(max_length=10)),
                ('QDesc', models.TextField()),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 10, 20, 15, 40, 287344))),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.AccountUser')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.Question'),
        ),
        migrations.AddField(
            model_name='answers',
            name='submitedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.AccountUser'),
        ),
    ]
