# Generated by Django 2.1.5 on 2019-02-10 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 10, 20, 17, 51, 362819)),
        ),
    ]
