# Generated by Django 2.1.7 on 2019-05-12 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0002_auto_20190325_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=30)),
                ('Scredit', models.CharField(max_length=2)),
                ('Ssemester', models.CharField(max_length=10)),
                ('Sprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.AccountUser')),
            ],
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='created',
            new_name='submitedAt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
