# Generated by Django 2.1.5 on 2019-02-10 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0002_auto_20190210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 10, 20, 41, 38, 426520)),
        ),
    ]
