# Generated by Django 2.1.7 on 2019-03-25 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0003_auto_20190210_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='document/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 25, 4, 35, 36, 257994)),
        ),
    ]
