# Generated by Django 2.1.7 on 2019-05-12 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniproject', '0003_auto_20190512_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='accountType',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='semester',
            field=models.CharField(default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Sprof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.Professor'),
        ),
    ]
