# Generated by Django 2.1.7 on 2019-03-25 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0004_auto_20190325_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 25, 4, 48, 32, 87136)),
        ),
    ]
