# Generated by Django 2.1.7 on 2019-05-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0005_auto_20190512_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='testcases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='input',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='output',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniproject.Question'),
        ),
    ]
