# Generated by Django 2.2.1 on 2019-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0007_auto_20190512_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='result',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='code',
            field=models.FileField(upload_to='submit'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FileField(upload_to='input'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FileField(upload_to='output'),
        ),
    ]
